# Generated by Django 6.0.6 on 2026-06-29 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_emailverificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_master_approved',
            field=models.BooleanField(default=False),
        ),
    ]
